blast: edit.undo()
not that: edit.undo()
yes that: edit.redo()
do it: edit.redo()
remove: user.clear_last_phrase()
nope: user.clear_last_phrase()
scratcher: user.clear_last_phrase()

big junk: user.edit_command("delete", "wordLeft")
bonk: user.edit_command("delete", "wordLeft")
swallow: user.edit_command("delete", "wordRight")

billy: edit.word_left()
willie: edit.word_right()
pasty: edit.paste()
paste raw: key(ctrl-shift-v)
yankee: edit.copy()
disky: edit.save()
